import Vue from 'vue';
import { Swipe, SwipeItem } from 'vant';

import { Tab, Tabs } from 'vant';
import { Cascader } from 'vant';
import { Field } from 'vant';
import { Popup } from 'vant';
import { Button, Cell } from 'vant';
import { IndexBar, IndexAnchor } from 'vant';
Vue.use(Cell);
Vue.use(IndexBar);
Vue.use(IndexAnchor);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Button);
Vue.use(Popup);
Vue.use(Field);
Vue.use(Cascader);
Vue.use(Tab);
Vue.use(Tabs);